name: CI

on: [push]

jobs:
  # Job name
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd mysqladmin ping
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8080:8080

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Setup environment variables
        run: |
          cp .env.example .env
          echo "NEXTAUTH_SECRET=supersecret" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Push schema to database
        run: npx prisma db push

      - name: Build application
        run: npm run build

      - name: Run all tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: |
          npm run lint
        env:
          SKIP_ENV_VALIDATION: true
